apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: us-payroll

resources:
  - namespace.yaml
  - edge-service.yaml
  - hr-service.yaml
  - tax-service.yaml
  - labor-service.yaml
  - payroll-orchestrator-service.yaml
  - payroll-worker-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: us-payroll-platform
