services:
  hr-service:
    ports:
      - "8081:8081"

  tax-service:
    ports:
      - "8082:8082"

  labor-service:
    ports:
      - "8083:8083"

  time-ingestion-service:
    ports:
      - "8084:8084"

  payroll-orchestrator-service:
    ports:
      - "8085:8085"

  payroll-worker-service:
    ports:
      - "8088:8088"
