apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-edge.yaml
  - pdbs.yaml
  - hpas.yaml
  - networkpolicies.yaml

patches:
  - path: replicas.patch.yaml
