apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: edge-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: edge-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-worker-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: billing-worker-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hr-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hr-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tax-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: tax-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: labor-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: labor-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: billing-orchestrator-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: billing-orchestrator-service
