apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres.yaml
  - secrets-dev.yaml

patches:
  - path: edge-service-lb.patch.yaml
    target:
      kind: Service
      name: edge-service
